# Generated by Django 4.0.5 on 2022-07-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.CharField(default='lettece', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
