# Generated by Django 4.0.4 on 2022-06-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ad',
            name='offer_date',
            field=models.DateField(),
        ),
    ]
