# Generated by Django 4.0.4 on 2022-06-29 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_ad_expiry_date_alter_ad_offer_date_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='user',
        ),
    ]
