# Generated by Django 4.0.4 on 2022-07-07 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_cart_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.ad'),
            preserve_default=False,
        ),
    ]
