# Generated by Django 4.0.4 on 2022-07-07 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_cart_ad_id_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ad_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='ad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.ad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_cost',
            field=models.IntegerField(default=1),
        ),
    ]
