# Generated by Django 4.0.4 on 2022-07-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_cart_quantity_remove_cart_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ad',
        ),
    ]
